
- name: install apt packages
  ansible.builtin.apt:
    update_cache: yes
    autoremove: yes
    name:
      - vim
      - jq
      - lsof
      - strace
      - sysstat
      - tcpdump
      - tmux
      - gcc
      - make
      - git
      - avahi-daemon
      - firewalld
    state: latest
